spring.application.name=trackinglogistico

spring.datasource.url=jdbc:postgresql://db.gbyackhgxtrmrytiaqpm.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=l6K87v04tqckFbXc
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080